import "./globals.css";
import Sidebar from "./components/Sidebar";
import { SidebarItem } from "./components/Sidebar";
import { House, UserPlus } from "lucide-react";
import Provider from "./util/Provider";

export const metadata = {
  title: "Comunidados - Redepharma",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className="flex">
        <Sidebar>
          <SidebarItem
            icon={<House size={20} />}
            text="Home"
            alert
            desiredUrl={"home"}
          />
          <SidebarItem
            icon={<UserPlus size={20} />}
            text="Cadastrar usuário"
            active
            desiredUrl={"user"}
          />
        </Sidebar>
        <main className="flex-1 p-6 bg-white">
          <Provider>{children}</Provider>
        </main>
      </body>
    </html>
  );
}
